name: Build and Deploy Project
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    #- name : Set up MYSQL
    #  uses : mirromutth/mysql-action@v1.1
    #  with :
    #    mysql database: 'dbacpfinal' # Optional, default value is "test". The specified database which will be create
    #    mysql root password: ${{ secrets.MYSQL_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
    #    mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
    #    mysql password: ${{ secrets.MYSQL_PASSWORD }} #
    # - name: Test
    #   run: go test ./business/users
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: arsyadthareeq/acp-final-golang:tagname

